version: '3.7'

services:
  web:
    build: .
    command: python order_management_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/order_management_api/
    ports:
      - 8999:8000
    env_file:
      - database.env
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=om_db
      - POSTGRES_PASSWORD=om_user
      - POSTGRES_DB=123qwe321
