version: '3.7'

services:
  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    expose:
      - 5454
    ports:
      - 5454:5454/tcp
    environment:
      - POSTGRES_USER=om_user
      - POSTGRES_PASSWORD=123qwe321
      - POSTGRES_DB=om_db
    command: -p 5454

  api:
    build: .
    command: python order_management_api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/order_management_api/
    ports:
      - 8923:8000
    depends_on:
      - postgresql

  migtation:
    build: .
    command: python order_management_api/manage.py migrate
    depends_on:
      - api

  swagger:
    image: nginx:1.17.4-alpine
    volumes:
      - ./swagger_doc:/usr/share/nginx/html
    ports:
      - "8323:80"

volumes:
  pgdata:
