# Generated by Django 2.2.4 on 2020-10-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20201012_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Successful'), (2, 'Unsuccessful')], db_index=True, default=0)),
                ('cash', models.BooleanField(default=False)),
                ('card', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField()),
                ('change', models.BigIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
