# Generated by Django 2.2.4 on 2020-10-13 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
